Style/FrozenStringLiteralComment:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Metrics/LineLength:
  Heredocs:
    Exclude: true

Metrics/AbcSize:
  Enabled: true
  Max: 11