#!/bin/sh

docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.12.yml build clean
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.12.yml run clean
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.14.yml build clean
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.14.yml run clean
