#!/bin/sh

docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.12.yml build compile
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.12.yml run compile
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.14.yml build compile
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.14.yml run compile
