#!/bin/sh

docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.12.yml build release
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.12.yml run release
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.14.yml build release
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.14.yml run release
