#!/bin/sh

docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.12.yml build shell
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.12.yml run shell
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.14.yml build shell
docker-compose -f docker-compose.common.yml -f docker-compose.glibc-2.14.yml run shell
